### ues balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### ues balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### Cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "7f51e4c013944b058fdec7981feeb5b7",
  "accountNumber": "1000000000",
  "amount": 20000
}

### query transaction
GET http://localhost:8080/transaction/7f51e4c013944b058fdec7981feeb5b7
Content-Type: application/json
